name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DoodleDigits

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build Core
      run: dotnet build DoodleDigits.Core
    - name: Build UnitTests
      run: dotnet build UnitTests
    - name: Test
      run: dotnet test --no-build --verbosity normal
